### ISSUE TITLE
User Story: participants in love running 

### ISSUE THREAD

**Issue by Christianalamassi** [Christianalamassi/First-agile#4]
As a **participant**  I can **see the running map** so that **I know where to buy water from, and how many miles to run**

## Tasks

- [ ]  Users are unable to log in if they use special characters in their passwords. Many users are unable to register for runs and meetups.

- [ ] Send an SMS message to remind participants 60 minutes before the run time. A few users reported that they do not show up because they forget.

- [ ]  Add a map for each running track and mark spots where runners can buy water from

- [ ] The “Sign up” button is not showing up properly on Android Tablets. Statistics show that more than 30% of website visitors are using Android Tablets.

- [ ] Include signup with social media networks to expedite the registration process. Note: Research suggests that the signup rate on websites increases by at least 120% with a social media network.

- [ ] Provide participants with the ability to mark their completion of a run and provide feedback, in addition to sharing their feedback on social media networks
